# Generated by Django 3.0.7 on 2020-06-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.TextField(editable=False, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
