# Generated by Django 3.0.7 on 2020-07-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
