# Generated by Django 3.0.7 on 2020-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200709_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='api_key',
            field=models.TextField(null=True, unique=True),
        ),
    ]
