# Generated by Django 3.0.8 on 2020-07-31 21:17

from django.db import migrations, models
from django.core.validators import MinLengthValidator


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200715_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=20, unique=True, validators=[MinLengthValidator(3)]),
        ),
    ]
