# Generated by Django 3.0.8 on 2020-08-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200731_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
