# Generated by Django 3.1.3 on 2020-12-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
