# Generated by Django 3.0.7 on 2020-07-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_squashed_0010_delete_mediaproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
