# Generated by Django 3.0.7 on 2020-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20200718_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
