# Generated by Django 3.1.3 on 2020-11-25 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploader.models
import uploader.validation

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0004_auto_20200718_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to=uploader.models.determine_media_path, validators=[uploader.validation.media_type_validator]),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
