# Generated by Django 3.1.3 on 2020-11-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20201125_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='identifier',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
