# Generated by Django 3.1.3 on 2020-12-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20201218_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.TextField(choices=[('image', 'Image'), ('video', 'Video')]),
        ),
    ]
