# Generated by Django 3.1.3 on 2020-12-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_auto_20201219_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='identifier',
            field=models.SlugField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
