# Generated by Django 3.1.3 on 2020-12-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_auto_20201219_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'permissions': [('custom_identifiers', 'Can have custom identifiers')], 'verbose_name_plural': 'media'},
        ),
    ]
