# Generated by Django 3.1.3 on 2020-12-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_auto_20201219_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='creation',
            new_name='created_at',
        ),
    ]
